name: app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4 
  sqflite: ^1.3.0
  path_provider: ^1.6.5
  fluttertoast: ^4.0.1
  pull_to_refresh: ^1.1.6
    

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    -  assets/images/
    
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Black.ttf
        - asset: assets/fonts/Lato/Lato-BlackItalic.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
        - asset: assets/fonts/Lato/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato/Lato-Hairline.ttf
        - asset: assets/fonts/Lato/Lato-HairlineItalic.ttf
        - asset: assets/fonts/Lato/Lato-Heavy.ttf
        - asset: assets/fonts/Lato/Lato-HeavyItalic.ttf
        - asset: assets/fonts/Lato/Lato-Italic.ttf
        - asset: assets/fonts/Lato/Lato-Light.ttf
        - asset: assets/fonts/Lato/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato/Lato-Medium.ttf
        - asset: assets/fonts/Lato/Lato-MediumItalic.ttf
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Semibold.ttf
        - asset: assets/fonts/Lato/Lato-SemiboldItalic.ttf
        - asset: assets/fonts/Lato/Lato-Thin.ttf
        - asset: assets/fonts/Lato/Lato-ThinItalic.ttf
    - family: Roboto_Mono
      fonts:
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Bold.ttf
        - asset: assets/fonts/Roboto_Mono/RobotoMono-BoldItalic.ttf
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Italic.ttf
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Light.ttf
        - asset: assets/fonts/Roboto_Mono/RobotoMono-LightItalic.ttf
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Medium.ttf
        - asset: assets/fonts/Roboto_Mono/RobotoMono-MediumItalic.ttf
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Regular.ttf
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Thin.ttf
        - asset: assets/fonts/Roboto_Mono/RobotoMono-ThinItalic.ttf
    - family: SarySoft
      fonts:
        - asset: assets/SarySoft/SarySoft-Light.ttf
        - asset: assets/SarySoft/SarySoft-SemiBold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
